Afl.print(`[*] Starting FRIDA config for PID: ${Process.id}`);

/* Modules to be instrumented by Frida, generated by harness generation */
const MODULE_WHITELIST = ["harness", GENERATOR_TARGETLIBRARIES];

/* Persistent hook */
const hook_module = new CModule(
    `
  #include <string.h>
  #include <gum/gumdefs.h>
  #define BUF_LEN 1048576

  void afl_persistent_hook(GumCpuContext *regs, uint8_t *input_buf,
    uint32_t input_buf_len) {
    uint32_t length = (input_buf_len > BUF_LEN) ? BUF_LEN : input_buf_len;
    memcpy((void *)regs->x[0], input_buf, length);
    regs->x[1] = length;
  }
  `,
    {
        memcpy: Module.getExportByName(null, "memcpy"),
    }
);

/* Persistent loop start address */
const pPersistentAddr = DebugSymbol.fromName("_Z14fuzz_one_inputPhm").address;

/* read the environemtn variables and sets the corresponding globals*/
var afl_area_ptr = Module.findExportByName('afl-frida-trace.so', '__afl_area_ptr');
afl_area_ptr = new Int64(afl_area_ptr.toString());
Afl.print(afl_area_ptr, typeof afl_area_ptr);
var set_afl_area_ptr = Module.findExportByName('libharness.so', '_Z16set_afl_area_ptrl');
Afl.print('loaded afl_set_area_ptr' + set_afl_area_ptr);
const func_set_afl_area_ptr = new NativeFunction(set_afl_area_ptr, 'void', ['long']);
Afl.print('loaded afl_set_area_ptr function' +  func_set_afl_area_ptr);
func_set_afl_area_ptr(afl_area_ptr);
Afl.print('set afl_area_ptr done');

/* read the environemtn variables and sets the corresponding globals*/
var printenv = Module.findExportByName('libharness.so', '_Z13hack_env_initv');
Afl.print('loaded hack_init_env' + printenv);
const func_printenv = new NativeFunction(printenv, 'void', []);
Afl.print('loaded hack_init_env function' +  func_printenv);
func_printenv();
Afl.print('init hack env done');

/* read the current memory map */
var readMaps_before = Module.findExportByName('libharness.so', '_Z15readMaps_beforev');
Afl.print('loaded readmapsbefore' + readMaps_before);
const func_readMaps_before = new NativeFunction(readMaps_before, 'void', []);
Afl.print('loaded readmapsbefore function' +  func_readMaps_before);
func_readMaps_before();
Afl.print('finished extracting the current memory maps');

/* load the android runtime, sets globals used by the harness */
var load_art = Module.findExportByName('libharness.so', '_Z8load_artv');
Afl.print('loaded load_art' + load_art);
const func_load_art = new NativeFunction(load_art, 'void', []);
Afl.print('loaded load_art function' +  func_load_art);
func_load_art();
Afl.print('finished load_art');

/* load the target library and set the base address*/
var load_targetlib = Module.findExportByName('libharness.so', '_Z18load_targetLibraryv');
Afl.print('loaded load_targetlib' + load_targetlib);
const func_load_targetlib = new NativeFunction(load_targetlib, 'void', []);
Afl.print('loaded load_targetlib function' +  func_load_targetlib);
func_load_targetlib();
Afl.print('init load_targetlib done');

var load_class0_object = Module.findExportByName('libharness.so', '_Z18load_class0_objectv');
Afl.print('loaded load_class0_object' + load_class0_object);
const func_load_class0_object = new NativeFunction(load_class0_object, 'void', []);
Afl.print('loaded func_load_class0_object function' +  func_load_class0_object);
func_load_class0_object();
Afl.print('finished func_load_class0_object');


/* load the libraries and exclude regions not of interest to us */
Module.load("libandroid_runtime.so");
Module.load("libart.so");
MODULE_WHITELIST.forEach((m) => {
    if(m != "harness"){
        Afl.print('loading apk library: ' + m);
        Module.load(m);
    }
});
new ModuleMap().values().forEach((m) => {
        if (!MODULE_WHITELIST.includes(m.name)) {
        Afl.print(`Exclude: ${m.base}-${m.base.add(m.size)} ${m.name}`);
        Afl.addExcludedRange(m.base, m.size);
    }
});

/* do the performance hack */
GENERATOR_PERFORMANCE_HACK


Afl.setEntryPoint(pPersistentAddr);
Afl.setPersistentHook(hook_module.afl_persistent_hook);
Afl.setPersistentAddress(pPersistentAddr);
Afl.setPersistentCount(1);
Afl.setInMemoryFuzzing();
Afl.setInstrumentLibraries(); 

Afl.done();
Afl.print("[*] All done!");