package aaa.bbb.ccc.path.analyses;

import aaa.bbb.ccc.Utils;
import soot.*;
import soot.jimple.*;
import soot.jimple.internal.ImmediateBox;
import soot.jimple.internal.JimpleLocal;
import soot.tagkit.StringTag;
import soot.tagkit.Tag;
import soot.toolkits.graph.DirectedGraph;
import soot.toolkits.scalar.*;

import java.lang.reflect.Parameter;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;


public class IntentPropagation extends ForwardFlowAnalysis
{
    private static final FlowSet<String> EMPTY_SET = new ArraySparseSet<String>();
    private final Map<Unit, FlowSet<String>> unitToGenerateSet;
    public Boolean returnIsIntentDp = false;

    public SootMethod method = null;
    public Boolean intentDependentExtractionOn = false;

    protected void copy(Object src, Object dest)
    {
        FlowSet srcSet  = (FlowSet) src;
        FlowSet destSet = (FlowSet) dest;

        srcSet.copy(destSet);
    }

    protected void merge(Object src1, Object src2, Object dest)
    {
        FlowSet srcSet1 = (FlowSet) src1;
        FlowSet srcSet2 = (FlowSet) src2;
        FlowSet destSet = (FlowSet) dest;

        srcSet1.union(srcSet2, destSet);
    }

    protected void flowThrough(Object in, Object unit,
                               Object out)
    {
        FlowSet outSet = (FlowSet) out;
        FlowSet inSet  = (FlowSet) in;
        Unit u = (Unit) unit;
        Stmt s = (Stmt) u;
        // outSet is inSet plus genSet
        inSet.union(unitToGenerateSet.get(u), outSet);

        if (s instanceof AssignStmt) {
            AssignStmt as = (AssignStmt) s;
            Value defValue = as.getLeftOp();
            if (outSet.contains(defValue.toString()) && !isIntentAttrExtraction(u)) {
                // KILL
                // Value is redefined if it is redefined but not generated by an unit in unitToGenerateSet
                // remove Value
                outSet.remove(defValue.toString());
            }
            if (!s.containsInvokeExpr()) {
                // GEN
                // assignment statement that is not a function call
                // where rhs contains tainted Value
                // taint lhs
                Value asRhs = as.getRightOp();
                if (asRhs instanceof Local || asRhs instanceof FieldRef || asRhs instanceof CastExpr) {

                    String genFact = null;
                    if (asRhs instanceof CastExpr) {
                        CastExpr asRhsCast = (CastExpr) asRhs;
                        genFact = asRhsCast.getOp().toString();
                    } else {
                        genFact = asRhs.toString();
                    }
                    if (outSet.contains(genFact)) {
                        // taint flow
                        outSet.add(defValue.toString());
                        if (intentDependentExtractionOn) {
                            Tag t = new StringTag("isIntentDependent");
                            u.addTag(t);
                        }
                    }
                } /*else {
                    List<ValueBox> uses = asRhs.getUseBoxes();
                    for (ValueBox vb : uses) {
                        if (outSet.contains(vb.getValue().toString())) {
                            // taint flow
                            outSet.add(defValue.toString());
                            if (intentDependentExtractionOn) {
                                Tag t = new StringTag("isIntentDependent");
                                u.addTag(t);
                            }
                        }
                    }
                }*/
            }
        }
        if (s.containsInvokeExpr()) {
            if (s instanceof AssignStmt) {
                AssignStmt assignStmt = (AssignStmt) u;
                Value defValue = assignStmt.getLeftOp();
                Value rhs = assignStmt.getRightOp();
                if (rhs instanceof InvokeExpr) {
                    InvokeExpr ie = (InvokeExpr)assignStmt.getRightOp();
                    if (ie instanceof InstanceInvokeExpr) {
                        // only InstanceInvokeExpr type has a callee base
                        InstanceInvokeExpr iie = (InstanceInvokeExpr) ie;
                        Value calleeBase = iie.getBase();
                        List<Value> calleeArgs = ie.getArgs();

                        if (outSet.contains(calleeBase.toString()) || (calleeArgs.size()==1 && outSet.contains(calleeArgs.get(0).toString()))) {
                            // GEN
                            // if a tainted Value is used as a callee base, taint lhs if it is a String
                            // can be because of String operation or other operations on the tainted object
                            // left taint.equals("x"), right "x".equals(taint)
                            SootMethod calledMethod = ie.getMethod();
                            String calledMethodClass = calledMethod.getDeclaringClass().getName();
                            if (Globals.stringOpsSet.contains(calledMethod.getName()) && calledMethodClass.equals("java.lang.String")) {
                                outSet.add(defValue.toString());
                                if (intentDependentExtractionOn) {
                                    Tag t = new StringTag("isIntentDependent");
                                    u.addTag(t);
                                }
                            } else if (calledMethod.getName().equals("intValue") && calledMethodClass.equals("java.lang.Integer")) {
                                outSet.add(defValue.toString());
                                if (intentDependentExtractionOn) {
                                    Tag t = new StringTag("isIntentDependent");
                                    u.addTag(t);
                                }
                            } else if (isIntentPayloadExtractionMethod(calledMethod, calledMethodClass)) {
                                outSet.add(defValue.toString());
                                if (intentDependentExtractionOn) {
                                    Tag t = new StringTag("isIntentDependent");
                                    u.addTag(t);
                                }
                            }
                        }
                    } else if (rhs instanceof StaticInvokeExpr) {
                        StaticInvokeExpr sie = (StaticInvokeExpr) rhs;
                        SootMethod calleeMethod = sie.getMethod();
                        if (calleeMethod.getDeclaringClass().getName().equals("java.lang.Integer") && calleeMethod.getName().equals("valueOf")) {
                            // primitive type such as Integer is represented as two statements:
                            // $i0 = virtualinvoke $r2.<android.content.Intent: int getIntExtra(java.lang.String,int)>("idata", 0)
                            // $r4 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>($i0)
                            // GEN
                            outSet.add(defValue.toString());
                            if (intentDependentExtractionOn) {
                                Tag t = new StringTag("isIntentDependent");
                                u.addTag(t);
                            }
                        }
                    }
                }
            }
        }

        if (s instanceof IfStmt) {
            for (ValueBox vb : s.getUseBoxes()) {
                Value val = vb.getValue();
                if (val instanceof JimpleLocal) {
                    if (outSet.contains(val.toString())) {
                        // ANNOTATE
                        // if-statement is data dependent on Intent
                        Tag t = new StringTag("isIntentDependent");
                        u.addTag(t);
                    }
                }
            }
        }
    }

    protected Object entryInitialFlow()
    {
        return EMPTY_SET.clone();
    }

    protected Object newInitialFlow()
    {
        return EMPTY_SET.clone();
    }

    public IntentPropagation(DirectedGraph g, SootMethod m, List<String> taintedArgs, Boolean intentDependentExtractionOn)
    {
        super(g);
        this.unitToGenerateSet = new HashMap<Unit, FlowSet<String>>(graph.size() * 2 + 1, 0.7f);
        this.method = m;

        Iterator unitIt = graph.iterator();
        while (unitIt.hasNext()){
            Unit u = (Unit) unitIt.next();
            Stmt s = (Stmt) u;

            FlowSet genSet = EMPTY_SET.emptySet();
            if (isIntentAttrExtraction(u)) {
                if (s instanceof AssignStmt) {
                    AssignStmt as = (AssignStmt) s;
                    Value payloadVar = as.getLeftOp();
                    genSet.add(payloadVar.toString(), genSet);
                }
            }
            if (s instanceof IdentityStmt) {
                // parameter is represented as an assignment statement
                if (!taintedArgs.isEmpty()) {
                    IdentityStmt is = (IdentityStmt) s;
                    if (is.getRightOp() instanceof ParameterRef) {
                        ParameterRef pr = (ParameterRef) is.getRightOp();
                        int prIndex = pr.getIndex();
                        if (taintedArgs.get(prIndex).equals("1") || taintedArgs.get(prIndex).equals("2")) {
                            // parameter is tainted
                            genSet.add(is.getLeftOp().toString(), genSet);
                        }
                    }
                }
            }
            if (intentDependentExtractionOn) {
                if (!genSet.isEmpty()) {
                    // use for -z flag (data-dependent path extraction)
                   // statement s generates facts
                    Tag t = new StringTag("isIntentDependent");
                    u.addTag(t);
                }
            }
            unitToGenerateSet.put(s, genSet);
        }
        doAnalysis();
    }

    private Boolean isIntentAttrExtraction(Unit u) {
        // Intent attribute extraction statement generates fact
        Stmt s = (Stmt) u;
        if (s instanceof AssignStmt) {
            if (s.containsInvokeExpr()) {
                InvokeExpr ie = Utils.getInvokeExprOfAssignStmt(u);
                if (ie == null) {
                    return false;
                }
                SootMethod calledMethod = ie.getMethod();
                //String calledMethodClass = calledMethod.getDeclaringClass().getName();
                if (calledMethod.getSubSignature().equals("android.content.Intent getIntent()")) {
                    // statement is getIntent()
                    return true;
                }
                /*
                else if (calledMethodClass.equals("android.content.Intent") ||
                        calledMethodClass.equals("android.os.Bundle") ||
                        calledMethodClass.equals("android.os.BaseBundle")) {
                    // statement is an Intent attribute extraction statement
                    if (isIntentPayloadExtractionMethod(ie.getMethod(), calledMethodClass)) {
                        return true;
                    }
                }
                 */
            }
        }
        return false;
    }

    public static Boolean isIntentPayloadExtractionMethod(SootMethod callee, String calledMethodClass) {

        String calleeName = callee.getName();
        //if (Pattern.matches("getScheme", calleeName)) {
        if (calleeName.equals("getScheme")) {
            // extracting URI scheme
            if (calledMethodClass.equals("android.net.Uri")) {
                return true;
            }
        }
        //if (Pattern.matches("getSchemeSpecificPart", calleeName)) {
        if (calleeName.equals("getSchemeSpecificPart")) {
            // extracting URI scheme
            if (calledMethodClass.equals("android.net.Uri")) {
                return true;
            }
        }
        //if (Pattern.matches("getHost", calleeName)) {
        if (calleeName.equals("getHost")) {
            // extracting URI host
            if (calledMethodClass.equals("android.net.Uri")) {
                return true;
            }
        }
        //if (Pattern.matches("toString", calleeName)) {
        if (calleeName.equals("toString")) {
            // extracting URI host
            if (calledMethodClass.equals("android.net.Uri")) {
                return true;
            }
        }
        //if (Pattern.matches("getData", calleeName)) {
        if (calleeName.equals("getData")) {
            // extracting URI. getData() returns URI
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
        if (Globals.getBundleMethodsSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
        //if (Pattern.matches("getDataString", calleeName)) {
        if (calleeName.equals("getDataString")) {
            // extracting URI as String. getDataString() returns URI
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }

        if (calleeName.startsWith("get") && calleeName.endsWith("Extra")) {
            // model array array variants now: nullness
            //if (Pattern.matches("get.*ArrayExtra", calleeName) ||
            //        Pattern.matches("get.*ArrayListExtra", calleeName)) {
            if (calleeName.endsWith("ArrayExtra") || calleeName.endsWith("ArrayListExtra")) {
                // we do model these
                if (calledMethodClass.equals("android.content.Intent")) {
                    return true;
                }
                //} else if (Pattern.matches("getSerializableExtra", calleeName) || Pattern.matches("getParcelableExtra", calleeName)) {
            } else if (calleeName.equals("getSerializableExtra") || calleeName.equals("getParcelableExtra")) {
                return true;
            }
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
        /*
        if (Globals.supportedExtrasSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
         */
        //if (Pattern.matches("hasExtra", calleeName)) {
        if (calleeName.equals("hasExtra")) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
        if (Globals.bundleExtraDataMethodsSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.os.Bundle") ||
                    calledMethodClass.equals("android.os.BaseBundle")) {
                return true;
            }
        }
        if (Globals.categoryMethodsSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
        //if (Pattern.matches("getAction", calleeName)) {
        if (calleeName.equals("getAction")) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return true;
            }
        }
        return false;
    }

}