package aaa.bbb.ccc.path.analyses;

import aaa.bbb.ccc.Utils;
import aaa.bbb.ccc.android.model.Uri;
import soot.*;
import soot.jimple.*;
import soot.jimple.internal.JimpleLocal;
import soot.tagkit.StringTag;
import soot.tagkit.Tag;
import soot.toolkits.graph.DirectedGraph;
import soot.toolkits.scalar.ArraySparseSet;
import soot.toolkits.scalar.FlowSet;
import soot.toolkits.scalar.ForwardFlowAnalysis;

import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;


public class IntentPropagationGranular extends ForwardFlowAnalysis
{
    private static final FlowSet<String> EMPTY_SET = new ArraySparseSet<String>();
    private final Map<Unit, FlowSet<String>> unitToGenerateSet;
    public Boolean returnIsIntentDp = false;

    public SootMethod method = null;
    public Boolean intentDependentExtractionOn = false;

    public class IntentFact {
        public String var = "";
        public String attr = "";

        public IntentFact(String var) {
            this.var = var;
        }

        public IntentFact(String var, String attr) {
            this.var = var;
            this.attr = attr;
        }

        public String getVar() {
            return this.var;
        }

        public String getAttr() {
            return this.attr;
        }

        public Boolean hasAttr() {
            return !this.attr.equals("");
        }

        public Boolean hasVar() {
            return !this.var.equals("");
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            IntentFact intentfact = (IntentFact) o;

            if (!var.equals(intentfact.var)) return false;
            return attr.equals(intentfact.attr);
        }

        @Override
        public int hashCode() {
            int result = var.hashCode();
            result = 31 * result + attr.hashCode();
            return result;
        }

    }

    protected void copy(Object src, Object dest)
    {
        FlowSet srcSet  = (FlowSet) src;
        FlowSet destSet = (FlowSet) dest;

        srcSet.copy(destSet);
    }

    protected void merge(Object src1, Object src2, Object dest)
    {
        FlowSet srcSet1 = (FlowSet) src1;
        FlowSet srcSet2 = (FlowSet) src2;
        FlowSet destSet = (FlowSet) dest;

        srcSet1.union(srcSet2, destSet);
    }

    protected void flowThrough(Object in, Object unit,
                               Object out)
    {
        FlowSet outSet = (FlowSet) out;
        FlowSet inSet  = (FlowSet) in;
        Unit u = (Unit) unit;
        Stmt s = (Stmt) u;
        // outSet is inSet plus genSet
        inSet.union(unitToGenerateSet.get(u), outSet);

        if (s instanceof AssignStmt) {
            AssignStmt as = (AssignStmt) s;
            Value defValue = as.getLeftOp();
            String varToCheck = defValue.toString();
            IntentFact asFact = containsWithoutAttrsRet(outSet, varToCheck);
            if (asFact != null && !isIntentAttrExtraction(u)) {
                // KILL
                // Value is redefined if it is redefined but not generated by an unit in unitToGenerateSet
                // remove Value
                outSet.remove(asFact);
            }
            if (!s.containsInvokeExpr()) {
                // GEN
                // assignment statement that is not a function call
                // where rhs contains tainted Value
                // taint lhs
                Value asRhs = as.getRightOp();
                if (asRhs instanceof Local || asRhs instanceof FieldRef || asRhs instanceof CastExpr) {
                    IntentFact rhsFact;
                    if (asRhs instanceof CastExpr) {
                        CastExpr asRhsCast = (CastExpr) asRhs;
                        rhsFact = containsWithoutAttrsRet(outSet, asRhsCast.getOp().toString());
                    } else {
                        rhsFact = containsWithoutAttrsRet(outSet, asRhs.toString());
                    }
                    if (rhsFact != null) {
                        // taint flow
                        if (rhsFact.hasAttr()) {
                            outSet.add(new IntentFact(defValue.toString(), rhsFact.getAttr()));
                        } else {
                            outSet.add(new IntentFact(defValue.toString()));
                        }
                        if (intentDependentExtractionOn) {
                            Tag t = new StringTag("isIntentDependent");
                            u.addTag(t);
                        }
                    }
                }
            }
        }
        if (s.containsInvokeExpr()) {
            if (s instanceof AssignStmt) {
                AssignStmt assignStmt = (AssignStmt) u;
                Value defValue = assignStmt.getLeftOp();
                Value rhs = assignStmt.getRightOp();
                if (rhs instanceof InvokeExpr) {
                    InvokeExpr ie = (InvokeExpr)assignStmt.getRightOp();
                    if (ie instanceof InstanceInvokeExpr) {
                        // only InstanceInvokeExpr type has a callee base
                        InstanceInvokeExpr iie = (InstanceInvokeExpr) ie;
                        Value calleeBase = iie.getBase();
                        List<Value> calleeArgs = ie.getArgs();

                        IntentFact calleeBaseFact = containsWithoutAttrsRet(outSet, calleeBase.toString());
                        IntentFact calleeArgFact = null;
                        if (calleeArgs.size()==1) {
                            calleeArgFact = containsWithoutAttrsRet(outSet, calleeArgs.get(0).toString());
                        }
                        if (calleeBaseFact!=null || calleeArgFact!=null) {
                            // GEN
                            // if a tainted Value is used as a callee base, taint lhs if it is a String
                            // can be because of String operation or other operations on the tainted object
                            // left taint.equals("x"), right "x".equals(taint)
                            IntentFact nonNullFact = null;
                            if (calleeBaseFact != null) {
                                nonNullFact = calleeBaseFact;
                            } else {
                                nonNullFact = calleeArgFact;
                            }
                            SootMethod calledMethod = ie.getMethod();
                            String calledMethodClass = calledMethod.getDeclaringClass().getName();
                            if (Globals.stringOpsSet.contains(calledMethod.getName()) && calledMethodClass.equals("java.lang.String")) {
                                if (nonNullFact.hasAttr()) {
                                    outSet.add(new IntentFact(defValue.toString(), nonNullFact.getAttr()));
                                } else {
                                    outSet.add(new IntentFact(defValue.toString()));
                                }
                                if (intentDependentExtractionOn) {
                                    Tag t;
                                    if (nonNullFact.hasAttr()) {
                                        t = new StringTag("isIntentDependent:" + nonNullFact.getAttr());
                                    } else {
                                        t = new StringTag("isIntentDependent");
                                    }
                                    u.addTag(t);
                                }
                            } else if (calledMethod.getName().equals("intValue") && calledMethodClass.equals("java.lang.Integer")) {
                                if (nonNullFact.hasAttr()) {
                                    outSet.add(new IntentFact(defValue.toString(), nonNullFact.getAttr()));
                                } else {
                                    outSet.add(new IntentFact(defValue.toString()));
                                }
                                if (intentDependentExtractionOn) {
                                    Tag t = new StringTag("isIntentDependent");
                                    u.addTag(t);
                                }
                            } else if (isIntentPayloadExtractionMethod(calledMethod, calledMethodClass) != null) {
                                String attr = isIntentPayloadExtractionMethod(calledMethod, calledMethodClass);
                                // generate attr
                                outSet.add(new IntentFact(defValue.toString(), attr));
                                if (intentDependentExtractionOn) {
                                    Tag t = new StringTag("isIntentDependent");
                                    u.addTag(t);
                                }
                            }
                        }
                    } else if (rhs instanceof StaticInvokeExpr) {
                        StaticInvokeExpr sie = (StaticInvokeExpr) rhs;
                        SootMethod calleeMethod = sie.getMethod();

                        if (calleeMethod.getDeclaringClass().getName().equals("java.lang.Integer") && calleeMethod.getName().equals("valueOf")) {
                            // primitive type such as Integer is represented as two statements:
                            // $i0 = virtualinvoke $r2.<android.content.Intent: int getIntExtra(java.lang.String,int)>("idata", 0)
                            // $r4 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>($i0)
                            // GEN
                            List<Value> calleeArgs = ie.getArgs();
                            if (calleeArgs.size()==1) {
                                IntentFact calleeArgFact = containsWithoutAttrsRet(outSet, calleeArgs.get(0).toString());
                                if (calleeArgFact != null) {
                                    if (calleeArgFact.hasAttr()) {
                                        outSet.add(new IntentFact(defValue.toString(), calleeArgFact.getAttr()));
                                    } else {
                                        outSet.add(new IntentFact(defValue.toString()));
                                    }
                                    if (intentDependentExtractionOn) {
                                        Tag t = new StringTag("isIntentDependent");
                                        u.addTag(t);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        if (s instanceof IfStmt) {
            for (ValueBox vb : s.getUseBoxes()) {
                Value val = vb.getValue();
                if (val instanceof JimpleLocal) {
                    IntentFact fact = containsWithoutAttrsRet(outSet, val.toString());
                    if (fact != null) {
                        // ANNOTATE
                        // if-statement is data dependent on Intent
                        Tag t;
                        if (!fact.attr.equals("")) {
                            // contains attribute
                            t = new StringTag("isIntentDependent" + ":" + fact.attr);
                            u.addTag(t);
                            break;
                        } /*else {
                            // does not contain attribute
                            t = new StringTag("isIntentDependent");
                        }*/
                        //u.addTag(t);
                    }
                }
            }
        }
    }

    protected Object entryInitialFlow()
    {
        return EMPTY_SET.clone();
    }

    protected Object newInitialFlow()
    {
        return EMPTY_SET.clone();
    }

    public IntentPropagationGranular(DirectedGraph g, SootMethod m, List<String> taintedArgs, Boolean intentDependentExtractionOn)
    {
        super(g);
        this.unitToGenerateSet = new HashMap<Unit, FlowSet<String>>(graph.size() * 2 + 1, 0.7f);
        this.method = m;

        Iterator unitIt = graph.iterator();
        while (unitIt.hasNext()){
            Unit u = (Unit) unitIt.next();
            Stmt s = (Stmt) u;

            FlowSet genSet = EMPTY_SET.emptySet();
            if (isIntentAttrExtraction(u)) {
                if (s instanceof AssignStmt) {
                    AssignStmt as = (AssignStmt) s;
                    Value payloadVar = as.getLeftOp();
                    genSet.add(new IntentFact(payloadVar.toString()), genSet);
                }
            }
            if (s instanceof IdentityStmt) {
                // parameter is represented as an assignment statement
                if (!taintedArgs.isEmpty()) {
                    IdentityStmt is = (IdentityStmt) s;
                    if (is.getRightOp() instanceof ParameterRef) {
                        ParameterRef pr = (ParameterRef) is.getRightOp();
                        int prIndex = pr.getIndex();
                        if (taintedArgs.get(prIndex).startsWith("1")) {
                            // parameter is tainted
                            String argType = taintedArgs.get(prIndex).split(":")[1];
                            genSet.add(new IntentFact(is.getLeftOp().toString(), argType), genSet);
                        } else if (taintedArgs.get(prIndex).equals("2")) {
                            genSet.add(new IntentFact(is.getLeftOp().toString(), "Intent"), genSet);
                        }
                    }
                }
            }
            if (intentDependentExtractionOn) {
                if (!genSet.isEmpty()) {
                    // use for -z flag (data-dependent path extraction)
                   // statement s generates facts
                    Tag t = new StringTag("isIntentDependent");
                    u.addTag(t);
                }
            }
            unitToGenerateSet.put(s, genSet);
        }
        doAnalysis();
    }

    private Boolean isIntentAttrExtraction(Unit u) {
        // Intent attribute extraction statement generates fact
        Stmt s = (Stmt) u;
        if (s instanceof AssignStmt) {
            if (s.containsInvokeExpr()) {
                InvokeExpr ie = Utils.getInvokeExprOfAssignStmt(u);
                if (ie == null) {
                    return false;
                }
                SootMethod calledMethod = ie.getMethod();
                //String calledMethodClass = calledMethod.getDeclaringClass().getName();
                if (calledMethod.getSubSignature().equals("android.content.Intent getIntent()")) {
                    // statement is getIntent()
                    return true;
                }
            }
        }
        return false;
    }

    public static IntentFact containsWithoutAttrsRet(FlowSet facts, String varToCheck) {
        for (Object fact : facts) {
            IntentFact intentfact = (IntentFact) fact;
            if (intentfact.getVar().equals(varToCheck)) {
                return intentfact;
            }
        }
        return null;
    }

    public static String isIntentPayloadExtractionMethod(SootMethod callee, String calledMethodClass) {

        String calleeName = callee.getName();
        if (Pattern.matches("getScheme", calleeName)) {
            // extracting URI scheme
            if (calledMethodClass.equals("android.net.Uri")) {
                return calleeName;
            }
        }
        if (Pattern.matches("getSchemeSpecificPart", calleeName)) {
            // extracting URI scheme
            if (calledMethodClass.equals("android.net.Uri")) {
                return calleeName;
            }
        }
        if (Pattern.matches("getHost", calleeName)) {
            // extracting URI host
            if (calledMethodClass.equals("android.net.Uri")) {
                return calleeName;
            }
        }
        if (Pattern.matches("toString", calleeName)) {
            // extracting URI host
            if (calledMethodClass.equals("android.net.Uri")) {
                return "URI"+calleeName;
            }
        }
        if (Pattern.matches("getData", calleeName)) {
            // extracting URI. getData() returns URI
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
        if (Globals.getBundleMethodsSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
        if (Pattern.matches("getDataString", calleeName)) {
            // extracting URI as String. getDataString() returns URI
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }

        if (calleeName.startsWith("get") && calleeName.endsWith("Extra")) {
            // model array array variants now: nullness
            //if (Pattern.matches("get.*ArrayExtra", calleeName) ||
            //        Pattern.matches("get.*ArrayListExtra", calleeName)) {
            if (calleeName.endsWith("ArrayExtra") || calleeName.endsWith("ArrayListExtra")) {
                // we do model these
                if (calledMethodClass.equals("android.content.Intent")) {
                    return calleeName;
                }
                //} else if (Pattern.matches("getSerializableExtra", calleeName) || Pattern.matches("getParcelableExtra", calleeName)) {
            } else if (calleeName.equals("getSerializableExtra") || calleeName.equals("getParcelableExtra")) {
                return null;
            }
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
        /*
        if (Globals.supportedExtrasSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
         */

        if (Pattern.matches("hasExtra", calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
        if (Globals.bundleExtraDataMethodsSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.os.Bundle") ||
                    calledMethodClass.equals("android.os.BaseBundle")) {
                return calleeName;
            }
        }
        if (Globals.categoryMethodsSet.contains(calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
        if (Pattern.matches("getAction", calleeName)) {
            if (calledMethodClass.equals("android.content.Intent")) {
                return calleeName;
            }
        }
        return null;
    }

}